import os
import json
import zipfile
from pathlib import Path
import sys

from encipherment.cipher import HomophonicCipher, MonoalphabeticCipher

TEST_MATRIX = {
    350: [5, 10, 15, 0],
    400: [5, 10, 15, 0],
    450: [5, 10, 15, 20, 0],
    600: [5, 10, 15, 20, 0],
    800: [5, 10, 15, 20, 25, 30, 0],
    1000: [5, 10, 15, 20, 25, 30, 0],
    2000: [5, 10, 15, 20, 25, 30, 50, 0],
    4000: [5, 10, 15, 20, 25, 30, 50, 100, 0],
    6000: [5, 10, 15, 20, 25, 30, 50, 100, 150, 0],
    8000: [5, 10, 15, 20, 25, 30, 50, 100, 200, 300, 0],
    10000: [5, 10, 15, 20, 25, 30, 50, 100, 200, 300, 0],
}


def adapt_key(train_key: dict, req_chars: set, target_mu: int) -> dict | None:
    """
    Takes a large training key and downsizes it to exactly target_mu symbols,
    ensuring every character in req_chars gets at least 1 symbol.
    """
    # 1. Ensure the training key actually has mappings for all required chars
    if not all(char in train_key and len(train_key[char]) > 0 for char in req_chars):
        return None

    # 2. Count how many symbols are available just among the required chars
    available_symbols = sum(len(train_key[char]) for char in req_chars)

    # 3. We can only downsize. If the training key doesn't have enough symbols, skip it.
    if available_symbols < target_mu:
        return None

    # 4. We must assign at least 1 symbol per character.
    if len(req_chars) > target_mu:
        return None

    new_key = {char: [] for char in req_chars}

    # Give every required character its first symbol
    for char in req_chars:
        new_key[char].append(train_key[char][0])

    # Distribute the remaining required symbols
    symbols_needed = target_mu - len(req_chars)

    for char in req_chars:
        if symbols_needed == 0:
            break
        # Add remaining symbols from this character's original training mappings
        for sym in train_key[char][1:]:
            if symbols_needed == 0:
                break
            new_key[char].append(sym)
            symbols_needed -= 1

    return new_key


def main():
    test_zip_path = Path("/ceph/project/SW10-CausalLM/Ciphers/Test/test_final.zip")
    training_dir = Path("/ceph/project/SW10-CausalLM/Ciphers/Training")
    output_file = Path("new_test_ciphers.jsonl")

    # --- PHASE 1: INITIALIZE TARGETS ---
    targets = {}
    for length, redundancies in TEST_MATRIX.items():
        for red in redundancies:
            bucket_id = f"{length}_{red}"
            targets[bucket_id] = {
                "length": length,
                "redundancy": red,
                "test_data": None,
                "req_chars": None,
                "target_mu": None,
                "completed": False,
            }

    missing_texts = len(targets)
    print(
        f"Phase 1: Extracting {missing_texts} test plaintexts from {test_zip_path.name}..."
    )

    # --- PHASE 2: COLLECT 81 TEST PLAINTEXTS ---
    if not test_zip_path.exists():
        print(f"Error: Could not find test zip at {test_zip_path}")
        sys.exit(1)

    with zipfile.ZipFile(test_zip_path, "r") as z:
        for filename in z.namelist():
            if not filename.endswith(".jsonl"):
                continue

            with z.open(filename, "r") as f:
                for line in f:
                    if missing_texts == 0:
                        break

                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    l = data.get("length")
                    r = data.get("redundancy")
                    bucket_id = f"{l}_{r}"

                    if bucket_id in targets and targets[bucket_id]["test_data"] is None:
                        targets[bucket_id]["test_data"] = data
                        targets[bucket_id]["req_chars"] = set(data.get("plaintext", ""))
                        # Get the exact mathematical mu generated by the native test cipher
                        targets[bucket_id]["target_mu"] = data.get("num_symbols")
                        missing_texts -= 1

            if missing_texts == 0:
                break

    if missing_texts > 0:
        print(
            f"Warning: Could not find plaintexts for {missing_texts} buckets in the test set!"
        )
        sys.exit(1)

    print("All 81 plaintexts acquired. Moving to training data search...\n")

    # --- PHASE 3: FIND MATCHING KEYS AND GENERATE ---
    missing_ciphers = len(targets)
    print(f"Phase 3: Scanning training data for valid keys...")

    with open(output_file, "w") as out_f:
        for zip_name in os.listdir(training_dir):
            if not zip_name.endswith(".zip"):
                continue

            zip_path = training_dir / zip_name
            print(f"Scanning {zip_name}...")

            with zipfile.ZipFile(zip_path, "r") as z:
                for filename in z.namelist():
                    if not filename.endswith(".jsonl"):
                        continue

                    with z.open(filename, "r") as f:
                        for line in f:
                            if missing_ciphers == 0:
                                break

                            try:
                                train_data = json.loads(line)
                            except json.JSONDecodeError:
                                continue

                            train_key = train_data.get("key", {})

                            # Check this key against our pending buckets
                            for bucket_id, info in targets.items():
                                if info["completed"]:
                                    continue

                                req_chars = info["req_chars"]
                                target_mu = info["target_mu"]

                                # Attempt to adapt the training key to fit this specific bucket perfectly
                                adapted_key = adapt_key(train_key, req_chars, target_mu)

                                if adapted_key is not None:
                                    # === MATCH FOUND! GENERATE THE CIPHER ===
                                    test_data = info["test_data"]
                                    plaintext = test_data.get("plaintext", "")
                                    length = info["length"]
                                    redundancy = info["redundancy"]

                                    text_obj = {
                                        "text": plaintext,
                                        "text_with_boundaries": test_data.get(
                                            "plaintext_with_boundaries", plaintext
                                        ),
                                        "length": length,
                                        "target_length": length,
                                        "genres": test_data.get("genres", []),
                                        "source_id": test_data.get(
                                            "source_id", "unknown"
                                        ),
                                        "source_name": test_data.get(
                                            "source_name", "unknown"
                                        ),
                                    }

                                    # Initialize the correct cipher
                                    if redundancy == 0:
                                        cipher = MonoalphabeticCipher(text_obj)
                                    else:
                                        cipher = HomophonicCipher(
                                            text_obj, redundancy=redundancy
                                        )

                                    # Inject the adapted training key
                                    cipher.key = adapted_key
                                    cipher.num_symbols = target_mu

                                    # Encipher and save
                                    cipher.encipher()
                                    out_f.write(json.dumps(cipher.__json__()) + "\n")

                                    info["completed"] = True
                                    missing_ciphers -= 1
                                    print(
                                        f"  [+] Match generated for N={length}, Red={redundancy}. {missing_ciphers} left."
                                    )
                                    break  # Prevent this key from being used by other buckets

                    if missing_ciphers == 0:
                        break
            if missing_ciphers == 0:
                break

    # --- PHASE 4: WRAP UP ---
    if missing_ciphers > 0:
        print(f"\nWarning: {missing_ciphers} buckets couldn't find a matching key.")
    else:
        print(
            f"\nSuccess! Generated all 81 test ciphers. Saved to {output_file.resolve()}"
        )


if __name__ == "__main__":
    main()
